name       : pcsc-tools
version    : 1.5.4
release    : 2
source     :
    - http://ludovic.rousseau.free.fr/softwares/pcsc-tools/pcsc-tools-1.5.4.tar.bz2 : c39e6abba781895220c68df5e5d2f0f9547c7a676eebec3f1ddcff8794377c93
license    : GPL-2.0-or-later
component  : security
summary    : Tools to be used with smart cards and PC/SC
description: |
    These tools are used to test a PC/SC driver, card or reader
    or send commands in a friendly environment (text or graphical user interface).
builddeps  :
    - pkgconfig(libpcsclite)
rundeps    :
    - pcsc-lite
    - perl-gtk3
    - perl-pango
    - perl-pcsc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 gscriptor.desktop $installdir/usr/share/applications/gscriptor.desktop

