name       : pcsc-tools
version    : 1.5.5
release    : 4
source     :
    - https://github.com/LudovicRousseau/pcsc-tools/archive/pcsc-tools-1.5.5.tar.gz : c30428d656e5261ee5a6115a745461170395fea582cf32ec035e85196c6be647
license    : GPL-2.0-or-later
component  : security
summary    : Tools to be used with smart cards and PC/SC
description: |
    These tools are used to test a PC/SC driver, card or reader
    or send commands in a friendly environment (text or graphical user interface).
builddeps  :
    - pkgconfig(libpcsclite)
rundeps    :
    - pcsc-lite
    - perl-gtk3
    - perl-pango
    - perl-pcsc
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 gscriptor.desktop $installdir/usr/share/applications/gscriptor.desktop

