name       : pcsc-tools
version    : 1.5.2
release    : 1
source     :
    - http://ludovic.rousseau.free.fr/softwares/pcsc-tools/pcsc-tools-1.5.2.tar.bz2 : ff4e087c76700aa5a25dd7d0bc4f55bb4a5e71cd4f0d6b5301babe0b434f86fc
license    : GPL-2.0
component  : security
summary    : Tools to be used with smart cards and PC/SC
description: |
    These tools are used to test a PC/SC driver, card or reader
    or send commands in a friendly environment (text or graphical user interface).
builddeps  :
    - pkgconfig(libpcsclite)
rundeps    :
    - pcsc-lite
    - perl-glib
    - perl-gtk2
    - perl-pango
    - perl-pcsc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m 0644 gscriptor.desktop $installdir/usr/share/applications/gscriptor.desktop

